<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.4.26230.115" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="11.0.0-preview.4.26230.115" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-preview.4.26230.115" />
    <PackageVersion Include="Spectre.Console" Version="0.55.2" />
    <PackageVersion Include="System.CommandLine" Version="3.0.0-preview.4.26230.115" />
    <PackageVersion Include="TUnit" Version="1.45.29" />
  </ItemGroup>
</Project>