<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.3.26207.106" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="11.0.0-preview.3.26207.106" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-preview.3.26207.106" />
    <PackageVersion Include="Spectre.Console" Version="0.55.0" />
    <PackageVersion Include="System.CommandLine" Version="3.0.0-preview.3.26207.106" />
    <PackageVersion Include="TUnit" Version="1.31.0" />
  </ItemGroup>
</Project>